### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FF_DWRD'

### ISSUE THREAD

**Issue by sh4m2hwz** [tmr232/Sark#100]
Python>import sark
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\sark\__init__.py", line 29, in <module>
    import core,code,exceptions,structure,codeblock,data,debug,enum,ui,graph
  File "C:\Python27\lib\site-packages\sark\structure.py", line 9, in <module>
    FF_TYPES = [idc.FF_BYTE, idc.FF_WORD, idc.FF_DWRD, idc.FF_QWRD, idc.FF_OWRD, ]
AttributeError: 'module' object has no attribute 'FF_DWRD'

**Comment by sh4m2hwz** [comment]
FF_TYPES = [idc.FF_BYTE, idc.FF_WORD, idc.FF_DWORD, idc.FF_QWORD, idc.FF_OWORD]

work for me
