### ISSUE TITLE
Problem installing on WIN-XP

### ISSUE THREAD

**Issue by ynvb** [tmr232/Sark#14]
I'm getting the following error when trying to install using pip:

```
Requirement already satisfied (use --upgrade to upgrade): awesomelib in c:\python27\lib\site-packages (from -r require
nts.txt (line 1))
Collecting yapsy (from -r requirements.txt (line 2))
  Using cached Yapsy-1.11.223.tar.gz
Collecting attrdict (from -r requirements.txt (line 3))
  Using cached attrdict-2.0.0.tar.gz
Collecting PyYAML (from -r requirements.txt (line 4))
  Using cached PyYAML-3.11.tar.gz
Obtaining Sark from git+https://github.com/tmr232/Sark.git#egg=Sark (from -r requirements.txt (line 5))
  Cloning https://github.com/tmr232/Sark.git to c:\tools\die\src\sark
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from attrdict->-r requ
ements.txt (line 3))
Collecting clipboard (from Sark->-r requirements.txt (line 5))
  Downloading clipboard-0.0.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): networkx in c:\python27\lib\site-packages (from Sark->-r req
rements.txt (line 5))
Collecting wrapt (from Sark->-r requirements.txt (line 5))
  Downloading wrapt-1.10.5.tar.gz
Collecting pyperclip>=1.3 (from clipboard->Sark->-r requirements.txt (line 5))
  Downloading pyperclip-1.5.24.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\docume~1\user\locals~1\temp\pip-build-3yjab7\pyperclip\setup.py", line 8, in <module>
        version=__import__('pyperclip').__version__,
      File "pyperclip\__init__.py", line 103, in <module>
        copy, paste = determine_clipboard()
      File "pyperclip\__init__.py", line 53, in determine_clipboard
        return init_windows_clipboard()
      File "pyperclip\windows.py", line 75, in init_windows_clipboard
        wcscpy_s = ctypes.cdll.msvcrt.wcscpy_s
      File "c:\python27\lib\ctypes\__init__.py", line 378, in __getattr__
        func = self.__getitem__(name)
      File "c:\python27\lib\ctypes\__init__.py", line 383, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: function 'wcscpy_s' not found

    ----------------------------------------
```

**Comment by tmr232** [comment]
Seems to be caused by asweigart/pyperclip/issues/51.

This is a dependency that is only relevant to the `quickcopy` plugin, so I might remove it from the requirements.

**Comment by tmr232** [comment]
@ynvb The Pyperclip issue is now resolved. Can you verify that this solves this issue?

**Comment by tmr232** [comment]
I am closing this due to lack of activity.
If this is still an issue for anyone - do tell me.
