### ISSUE TITLE
OSX Installation Issues

### ISSUE THREAD

**Issue by bdemick** [tmr232/Sark#41]
Getting errors when importing in IDA after pip installation (IDA 6.9.151221, OS X 10.11.4): 

```
Python>import sark
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/sark/__init__.py", line 28, in <module>
    from . import (core,
  File "/Library/Python/2.7/site-packages/sark/codeblocks.py", line 2, in <module>
    import networkx
  File "/Library/Python/2.7/site-packages/networkx/__init__.py", line 68, in <module>
    import networkx.utils
  File "/Library/Python/2.7/site-packages/networkx/utils/__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "/Library/Python/2.7/site-packages/networkx/utils/decorators.py", line 7, in <module>
    from decorator import decorator
ImportError: No module named decorator
```

```
Python>import sark
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/sark/__init__.py", line 28, in <module>
    from . import (core,
  File "/Library/Python/2.7/site-packages/sark/codeblocks.py", line 2, in <module>
    import networkx
  File "/Library/Python/2.7/site-packages/networkx/__init__.py", line 43, in <module>
    from networkx import release
ImportError: cannot import name release
```

Not sure how to fix this one!  Looks like it changes on subsequent attempts to import.

**Comment by tmr232** [comment]
You might be able to use some of the ideas here - https://github.com/tmr232/Sark/issues/13#issuecomment-203789419

I can't help too much as I don't have IDA on OSX, but I recommend making sure you can import all of Sark's dependencies.

**Comment by tmr232** [comment]
Is this still relevant?

**Comment by bdemick** [comment]
Haven't come back around to try the recommendations; will do that shortly.
