### ISSUE TITLE
Highlight calls plugin broken

### ISSUE THREAD

**Issue by stevemk14ebr** [tmr232/Sark#90]
Ida 7.5 + python3

```
[PluginLoader] Loading plugins from system-wide and user-specific lists:
[PluginLoader]   System-wide List:      C:\Program Files\IDA Pro 7.5\cfg\plugins.list
[PluginLoader]   User-specific List:    C:\Users\stephen.eckels\AppData\Roaming\Hex-Rays\IDA Pro\plugins.list
[PluginLoader]   Project-specific List: C:\Users\stephen.eckels\Desktop\labs\plugins.list
[PluginLoader] Failed creating system plugin list at C:\Program Files\IDA Pro 7.5\cfg\plugins.list
C:\Users\stephen.eckels\source\repos\Sark\plugins\highlight_calls.py: string argument without an encoding
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.5\python\3\ida_idaapi.py", line 604, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/stephen.eckels/source/repos/Sark/plugins/highlight_calls.py", line 4, in <module>
    from ida_settings import IDASettings
  File "C:\Users\stephen.eckels\AppData\Local\Programs\Python\Python37\lib\site-packages\ida_settings\__init__.py", line 1, in <module>
    from .ida_settings import IDASettings, PermissionError
  File "C:\Users\stephen.eckels\AppData\Local\Programs\Python\Python37\lib\site-packages\ida_settings\ida_settings.py", line 859, in <module>
    VALUE_1 = bytes("hello")
TypeError: string argument without an encoding

```

**Comment by stevemk14ebr** [comment]
I see this is related to ida_settings not being up to date on pypi, i've installed locally instead. The script now loads successfully, however when executing it nothing is highlighted (and no errors are reported), any ideas?

**Comment by stevemk14ebr** [comment]
User error, had to toggle in view menu. I've messaged Willi about publishing new version of ida_settings
